#!/bin/bash

# Get all active IPv4 interfaces
interfaces=$(ip -4 addr | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | grep -v '127.0.0.1')

# Display the IPs
for ip in $interfaces; do
    echo "$ip"
done
